# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5fc2a7f580b1c0c8c412799d523fa35e325fed0efac76b5539b2378d1a029b2811a1d2daaaa695b789c9b41be166fdb8462fe91717a57ec355b9fecaef5d0be

test:
  secret_key_base: d8d0b9396950705d60cba3c0472e79fadbec82e0c24211ecc633f5d8348141f8b49ee53cf927e5d67b0d6082422a1ea97fe2e0afbd726e849021bca27e639566

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
